In [5]:
# import the libraries.
import cv2
import numpy as np
import face_recognition
import os

In [6]:


path = "imgfold"
images = []
classNames = []
mylist = os.listdir(path) # get all the images from "imgfold" folder.
 
for i in mylist:
    curImg = cv2.imread(f'{path}/{i}') # current images(curImg).
    images.append(curImg)
    classNames.append(os.path.splitext(i)[0]) # split the images name and get without jpeg.
     
print(mylist)    
print(classNames)    

['akshay .jpeg', 'akshay.jpeg', 'shahrukh.jpg']
['akshay ', 'akshay', 'shahrukh']


In [7]:
# now encode the all images.

def encodeimg(images):
    encodelist = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodelist.append(encode)
    return encodelist
ENCODE = encodeimg(images)
print("encoding is done.")

encoding is done.


In [ ]:
# enable the camera.

cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
    imgsmall = cv2.resize(img, (0,0), None, 0.25, 0.25) # (image, pixelsize, None , scale)
    imgsmall = cv2.cvtColor(imgsmall, cv2.COLOR_BGR2RGB)
    FacelocCurFrame = face_recognition.face_locations(imgsmall) # face location in current frame.
    EncodeCurFrame = face_recognition.face_encodings(imgsmall, FacelocCurFrame) # encode the current frame.
    
    for encodeface , facelocation in zip(EncodeCurFrame, FacelocCurFrame):
        matching = face_recognition.compare_faces(ENCODE, encodeface)
        facedist = face_recognition.face_distance(ENCODE, encodeface)
        #print(facedist)
        matchindex = np.argmin(facedist)
        
        if matching[matchindex]:
            name = classNames[matchindex].upper()
            #print(name)
            y1, x1, y2, x2 = facelocation
            y1, x1, y2, x2 = y1*4, x1*4, y2*4, x2*4
            cv2.rectangle(img, (x1,y1), (x2,y2), (0,255,0), 2)
            cv2.rectangle(img, (x1,y2-35), (x2,y2), (0,255,0), cv2.FILLED)
            cv2.putText(img, name, (x1+6, y2-6), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 2 )
            
            
    cv2.imshow('webcam', img)
    cv2.waitKey(1)

[0.68354966 0.65488328 0.82369726]
[0.7344296  0.69594751 0.60586385]
[0.72744926 0.71203642 0.51075206]
[0.67952957 0.63346649 0.52938703]
[0.68736216 0.69800205 0.44254935]
[0.7662904  0.76316439 0.45110804]
[0.71990054 0.70543621 0.46284254]
[0.72714133 0.72801121 0.40877268]
[0.74637472 0.7521446  0.46419866]
[0.71828747 0.72280463 0.67668731]
[0.69917788 0.73684177 0.70200405]
[0.69556506 0.73949673 0.68616159]
[0.71911306 0.72746699 0.69763927]
[0.66513798 0.6787892  0.6429676 ]
